apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-persons
  name: udaconnect-api-persons
spec:
  selector:
    service: udaconnect-api-persons
  type: NodePort
  ports:
  - name: "rest"
    port: 5003
    nodePort: 30003
  - name: "grpc"
    port: 5004
    nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-persons
  name: udaconnect-api-persons
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-persons
  template:
    metadata:
      labels:
        service: udaconnect-api-persons
    spec:
      containers:
      - image: elenakutanov/udaconnect-api-persons:latest
        name: udaconnect-api-persons
        ports:
        - containerPort: 5003
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      - image: elenakutanov/udaconnect-api-persons-grpc:latest
        name: udaconnect-persons-grpc-server
        ports:
        - containerPort: 5004
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
