apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-kafka-broker
  name: udaconnect-kafka-broker
spec:
  selector:
    service: udaconnect-kafka-broker
  type: NodePort
  ports:
  - name: "zookeeper"
    port: 5008
    targetPort: 5008
  - name: "broker"
    port: 5007
    targetPort: 5007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-kafka-broker
  name: udaconnect-kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-kafka-broker
  template:
    metadata:
      labels:
        service: udaconnect-kafka-broker
    spec:
      containers:
      - image: elenakutanov/udaconnect-kafka-broker:latest
        name: udaconnect-kafka-zookeeper
        ports:
        - containerPort: 5008
      - image: elenakutanov/udaconnect-kafka-broker:latest
        name: udaconnect-kafka-broker
        ports:
        - containerPort: 5007
