apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-kafka
  name: udaconnect-kafka
spec:
  ports:
  - name: "5005"
    port: 5005
  selector:
    service: udaconnect-kafka
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-kafka
  name: udaconnect-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-kafka
  template:
    metadata:
      labels:
        service: udaconnect-kafka
    spec:
      containers:
      - image: elenakutanov/udaconnect-kafka:latest
        name: udaconnect-kafka
        command: ["docker", "exec", "broker", "kafka-topics", "--bootstrap-server", "broker:9092", "--create", "--topic", "udaconnect"]
