apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-kafka-producer
  name: udaconnect-kafka-producer
spec:
  ports:
  - name: "5006"
    port: 5006
    nodePort: 30006
  selector:
    service: udaconnect-kafka-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-kafka-producer
  name: udaconnect-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-kafka-producer
  template:
    metadata:
      labels:
        service: udaconnect-kafka-producer
    spec:
      containers:
      - image: elenakutanov/udaconnect-kafka-producer:latest
        name: udaconnect-kafka-producer
